import { Roboto } from "next/font/google"; // Import Roboto font
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={roboto.className}>
        {children}
      </body>
    </html>
  );
}
